### ISSUE TITLE
Duplication Glitch

### ISSUE THREAD

**Issue by adellacanonica** [CottonMC/EpicureanGastronomy#12]
When you add Jelly to an item it essentially duplicates the whole stack. 

For example, 

I have a stack of Cooked Pork Chops,
I input one full stack plus 5 Jelly,
The output is One full stack of Jellied Pork Chops but the recipe only used one Pork Chop and one Jelly. I am on the latest version.

**Comment by apotheoseGrifter** [comment]
Got this same glitch. Host of our LAN session managed to fill their entire inventory by shift-clicking a stack.

**Comment by LemmaEOF** [comment]
Hm. I'll take a look. I had something like this with meal crafting, so I should be able to fix this at least moderately quickly.
