### ISSUE TITLE
Crops don't provide drops

### ISSUE THREAD

**Issue by lizfinite** [CottonMC/EpicureanGastronomy#17]
With the most recent mod version, 2.2.0; crops no longer give player the items when right clicking or destroying them. 

Steps to reproduce:

1.  Enter a save or new world
2.  Find or give tomato/onion seeds & bonemeal
3.  Grow plant and try to harvest. 

Tested with only required dependencies, so no other mods are conflicting. 
Lastest Fabric Loader Build and API build. 

There are no errors produced within the logs that I can see in multiMC.

**Comment by LemmaEOF** [comment]
Hm. I'm having them drop fine in development, so I might need to take a look at Epicurean's data pack and see what's up with it. For right-click harvesting it might be something with the `activate()` code, but I have no idea why it wouldn't be working for breaking. I'll keep you posted.

**Comment by trollsdottir** [comment]
I have the same issue. Yesterday it was working alright, but after updating to the newest Fabric API the bug occurred.

**Comment by LemmaEOF** [comment]
oh boy it's something with fabric api. I'll take a look

**Comment by trollsdottir** [comment]
After updating to newest fabric API again blocks don't drop from at least two other mods (Cotton Resources and Extra Pieces), I thought I give the info to the coders. It may be some wider problem

**Comment by LemmaEOF** [comment]
I believe this has been fixed with 0.3.0+build.173.
