### ISSUE TITLE
Clientside crash

### ISSUE THREAD

**Issue by Luxley** [CottonMC/EpicureanGastronomy#18]
Made a beef stew with tomato and dandelions as seasonings.
Attempted to hold it in hand and went straight to crash.
On a 1.14 server im running.

[crash-2019-05-22_00.53.39-client.txt](https://github.com/CottonMC/EpicureanGastronomy/files/3205798/crash-2019-05-22_00.53.39-client.txt)
[latest.log](https://github.com/CottonMC/EpicureanGastronomy/files/3205800/latest.log)

**Comment by LemmaEOF** [comment]
It looks like there's an incompatibility with Console Hud. I'll talk to the dev about it. File this there too.
