### ISSUE TITLE
Crash on World loading with latest Fabric API

### ISSUE THREAD

**Issue by lizfinite** [CottonMC/EpicureanGastronomy#19]
Updated to the most recent Fabric Build in my mod pack and started getting a crash on world load. 
Something about:
`Int2ObjectMap contained two equal IDs 0 (minecraft:air/837 -> minecraft:air/0)!`

Tested with:

- Fabric Loader 0.4.8 154 Minecraft 1.14.2
- Fabric API Build 173
- Cotton 0.6.7, as [#24](https://github.com/CottonMC/cotton/issues/24) of Cotton is still open and I can't seem to find any those hot fix builds yet ;)

[Pastebin Crash (No mods besides dependencies)](https://pastebin.com/94mK93jD)

**Comment by LemmaEOF** [comment]
The hotfix builds have replaced the broken builds. I've been running into this air issue for a while and I have no idea what's been causing it.

**Comment by Knito58** [comment]
I could not load my saved worlds again and after long investigating I isolated this mod as the cause. I'm very sorry because I tend to use the farming hoppers a lot.
https://pastebin.com/2T4VtqKS

**Comment by LemmaEOF** [comment]
I still don't know what's going on here.

**Comment by Knito58** [comment]
I only found a hint about "air" in the DesertCropFeature.java
Maybe disabling this class in a test build for 1.14.2 leads to loadable world saves?

**Comment by LemmaEOF** [comment]
No, [this is happening outside of the air bug too](https://github.com/CottonMC/EpicureanGastronomy/issues/20). I think it might be something with Fabric API.

**Comment by Knito58** [comment]
Ok. I see.

**Comment by Sammagoat** [comment]
I am having the same issue, but with different IDs (minecraft:air/696 -> minecraft:air/0). I'm also running Fabric 0.4.8 for MC 1.14.2. Not sure if that info will help at all.

**Comment by LemmaEOF** [comment]
I believe this may be an issue with the new fabric API.

**Comment by LemmaEOF** [comment]
This is indeed a Fabric API issue.
