### ISSUE TITLE
Clientside crash while trying to load into server.

### ISSUE THREAD

**Issue by Luxley** [CottonMC/EpicureanGastronomy#20]
I updated both client and server sides from 1.14 to 1.14.1

[crash-2019-05-29_19.48.46-client.txt](https://github.com/CottonMC/EpicureanGastronomy/files/3234992/crash-2019-05-29_19.48.46-client.txt)

**Comment by TimGoll** [comment]
it's the same as #19

**Comment by TimGoll** [comment]
Downgrading to fabric API solved the problem for me

**Comment by LemmaEOF** [comment]
Oh boy, is this because of the new registry API? I'll have to see what needs to be changed.

**Comment by TimGoll** [comment]
Version 170 is the newest version that works for me, 171+ crashes

**Comment by Luxley** [comment]
Hey do either of you know if any of the recent versions of Epicurean and the API works?

**Comment by LemmaEOF** [comment]
The issue with fabric API has not yet been fixed.

**Comment by Luxley** [comment]
Okay im gonna try running it on the latest verisons api:0.3.0 build .179 and epicurean 2.2.0

**Comment by Luxley** [comment]
Still broken!

[crash-2019-06-06_17.00.42-client.txt](https://github.com/CottonMC/EpicureanGastronomy/files/3263666/crash-2019-06-06_17.00.42-client.txt)

**Comment by LemmaEOF** [comment]
As I *just* said, fabric API is not fixed.

**Comment by LemmaEOF** [comment]
Actually, looking at that log, that's not even from Epicurean. I'm closing this issue and forwarding that log to the Fabric API issue.
