### ISSUE TITLE
[Minecraft 1.4.4] Recipe error causes strange behavior

### ISSUE THREAD

**Issue by notfood** [CottonMC/EpicureanGastronomy#21]
Datapack that contains the epicurean:umami is causing the server to error and stop loading datapacks. This issue only happens on dedicated servers, it's possible it's a 1.4.4 issue, the missing recipe may only be bringing the underlying issue up. Removing Epicurean Gastronomy makes the issue go away.

**To Reproduce**
1. Run Dedicated Server 1.4.4
2. Meet any tree
3. Watch as tree decays

**Screenshots**
![image](https://user-images.githubusercontent.com/5370107/61570675-e73c3180-aa53-11e9-83c4-edb0bfd50da8.png)

**Versions:**
 - Epicurean Gastronomy 2.2.3
 - Fabric Loader 0.4.8+build.155
 - Fabric API 0.3.0 build 200
 - Minecraft 1.4.4

**Additional info**
[log.txt](https://github.com/CottonMC/EpicureanGastronomy/files/3413010/log.txt)

**Comment by LemmaEOF** [comment]
You have Cotton in, right? Epicurean depends on it, but I made a typo in the fabric.mod.json that's preventing it from throwing a mod resolution exception if it's missing. Cotton provides tags that Epicurean uses, and Minecraft has some aggravating cascading-failure bugs that happen with data packs. Install Cotton and see if that fixes things.

**Comment by notfood** [comment]
Yeah, cotton@1.0.0-rc.2 is loaded.

**Comment by LemmaEOF** [comment]
Hm, I’ll take a look at Cotton. Worse comes to worst, I can just add the tags to epicurean.

**Comment by LemmaEOF** [comment]
I've found the issue! The tags somehow never made it to the modularized system. I've re-added them; now everything should (hopefully) work fine!
