### ISSUE TITLE
soybean soysauce and tofu no texture/localization

### ISSUE THREAD

**Issue by breadguyyy** [CottonMC/EpicureanGastronomy#3]
all 3 have missing textures (black and purple square) and the item names are something like "item.epicurean.soybean"

also this is probably intentional but its a little weird to have the moldy jellies still there just crossed out and under the old mod name. 

other than that this is a great mod! thank you!

**Comment by LemmaEOF** [comment]
The moldy jellies are there to prevent people who used the old version of the mod, Edibles, from losing any of their items from it. They will eventually be removed once I feel enough time has passed.

Soybeans, Soy sauce, and Tofu are not yet implemented. There is no way to get them currently, and I haven't commissioned textures for them or the soy plant yet. They will be properly added in a future update.

I'm not yet sure how to programmatically hide items in REI, but once I know how, the deprecated items will no longer appear in it.  Soy products will be available in the 2.2.x update.
