### ISSUE TITLE
The crop block from epicurean should call super for appendProperties implementation

### ISSUE THREAD

**Issue by liach** [CottonMC/EpicureanGastronomy#30]
**Describe the bug**
The crop block from epicurean should call `super` for `appendProperties` implementation.

https://github.com/CottonMC/Epicurean/blob/7785185002e3d87cb79bd9087131555151634eec/src/main/java/io/github/cottonmc/epicurean/block/crop/HarvestableCropBlock.java#L71

This apparently causes crashes with other mods that add properties to all crop blocks, such as demeter. [demeters' addition](https://github.com/Wtoll/demeter/blob/0d09aefbcbdd6553bf744fe175f2cf6ade592822/src/main/java/com/wtoll/demeter/mixin/CropBlockMixin.java#L50) See Wtoll/demeter#13

**To Reproduce**
1. Install both demeter and epicurean
2. Plant epicurean block and crash

**Expected behavior** *Optional*
The epicurean crop block should include properties from base crop block

**Version of the (please complete the following information):**
See Wtoll/demeter#13

**Comment by LemmaEOF** [comment]
ah yeah, I didn't think of this when I wrote this code. I'll fix this when I have time.

**Comment by liach** [comment]
Fyi this one needs updating as well https://github.com/CottonMC/Epicurean/blob/26a1eb9f0430da9632c18c374e63c7e02a8a8fce/src/main/java/io/github/cottonmc/epicurean/block/crop/PickableCropBlock.java#L18-L21

**Comment by LemmaEOF** [comment]
I don't know if I can call to super on PickableCropBlock#appendProperties, sadly, as that would then force it to add `Properties.AGE_7` as well, which I do *not* want. I'll try it, but if it breaks things I'm reverting.
