### ISSUE TITLE
2.1.1 server crash with All of Fabric modpack

### ISSUE THREAD

**Issue by ImAK9** [CottonMC/EpicureanGastronomy#4]
https://pastebin.com/3asHJWUH

**Comment by SDUBZ** [comment]
loader version : fabric-loader-0.4.2+build.132.jar
minecraft: 1.14
epicurean gastronomy version : 2.1.1+1.14.jar


[latest.txt](https://github.com/CottonMC/EpicureanGastronomy/files/3113647/latest.txt)
log file with detailed parts of crashing

**Comment by LemmaEOF** [comment]
@SDUBZ I'm not seeing anywhere in that log related to that crash, all the errors I'm seeing are recipe jsons not loading.

@AK9Official Is there a specific item this crashed with? That'll help me narrow this down a lot.

**Comment by ImAK9** [comment]
@Boundarybreaker It crashes on server boot. It didn't with 2.1.0

**Comment by LemmaEOF** [comment]
Ah. I know what's up, then.

**Comment by Frontrider** [comment]
The maximum that I can see is some form of hammer mod. There is nothing in any of those logs pointing at this mod.

**Comment by SDUBZ** [comment]
sorry @Boundarybreaker that was the client not server log  heers the server log
[latest.txt](https://github.com/CottonMC/EpicureanGastronomy/files/3114267/latest.txt)
