### ISSUE TITLE
Crash on server start up (1.14) Mixin apply failed epicurean.client.json:MixinIngredientTooltips -> net.minecraft.class_1792: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException Unexpecteded NullPointerException whilst applying the mixin class: null

### ISSUE THREAD

**Issue by SDUBZ** [CottonMC/EpicureanGastronomy#5]
Fabric: fabric-loader-0.4.2+build.132
minecraft: 1.14
EG: epicurean-gastronomy-2.1.1+1.14
latest log:
[latest.txt](https://github.com/CottonMC/EpicureanGastronomy/files/3115497/latest.txt)

**Comment by LemmaEOF** [comment]
Fixed in 2.1.2, update your Epicurean version.
