### ISSUE TITLE
crash on dedicated servers due to environment annotation missing

### ISSUE THREAD

**Issue by LemmaEOF** [CottonMC/EpicureanGastronomy#6]
https://gist.github.com/raphydaphy/9c8b2cc77efb038f726c39e6e222bc92

put an `@Environment` annotation on cloth config init and move the code that calls it into ClientModInitializer

also either delete the recipe book group mixin or move it to client json

**Comment by ImAK9** [comment]
I guess this is the same crash? https://pastebin.com/kxuuNuKD

**Comment by LemmaEOF** [comment]
Nope, that's something from Fabric API.

**Comment by Juuxel** [comment]
AK9's log also has this at the top: `@Mixin target net.minecraft.class_299 was not found epicurean.common.json:MixinRecipeBookGroups`

**Comment by LemmaEOF** [comment]
Yes, but that's not the cause of the crash. I will be fixing that at the same time though.
